List<Map<String, dynamic>> shoppingList = [
  {
    'image': 'assets/images/tag.webp',
    'title': 'Tags_Regular',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 0,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Tags_Premium',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 20,
  },
  {
    'image': 'assets/images/face.webp',
    'title': 'Face Attendance',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 100,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Belts_Regular',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Belts_Premium',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Ties_Regular',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/ties.webp',
    'title': 'Ties_Premium',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/idcard.webp',
    'title': 'Smart ID Card',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/students.webp',
    'title': 'Registration',
    'rating': 5.0,
    'days': 'Delivery in 1 days',
    'rate': 5040,
  },
  {
    'image': 'assets/images/students.webp',
    'title': 'SMS',
    'rating': 5.0,
    'days': 'Delivery in 1 days',
    'rate': 0,
  },
  {
    'image': 'assets/images/profile.webp',
    'title': 'Kid Fit',
    'rating': 5.0,
    'days': 'Delivery in 30 days',
    'rate': 100,
  },
  {
    'image': 'assets/images/profile.webp',
    'title': 'Cub Codes',
    'rating': 5.0,
    'days': 'Delivery in 90 days',
    'rate': 1300,
  },
];
List<Map<String,dynamic>> tags = [
  {
    'image': 'assets/images/tag.webp',
    'title': 'Dark Blue',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Yellow',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Light Blue',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Milatary Green',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Parrot Green',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Red',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Maroon',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Purple',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Orange',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tag.webp',
    'title': 'Brown',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
];
List<Map<String,dynamic>> face_Attendance = [
{
'image': 'assets/images/belt.jpg',
'title': 'Al_Model-1 (Below 300)',
'rating': 5.0,
'days': 'Delivery in 14 days',
'rate': 100,
},
{
'image': 'assets/images/belt.jpg',
'title': 'Al_Model-2 (Above 300)',
'rating': 5.0,
'days': 'Delivery in 14 days',
'rate': 100,
},
];
List<Map<String,dynamic>> beltsRegular = [
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Red_White',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Red_Cream-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Maroon_White',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Maroon_Cream-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Maroon_White-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Light Blue_White-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Grey_White',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'DarkGrey_Red',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'DarkBlue_White',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Brown_Cream',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'DarkBlue_White',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Blue_Red',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Blue_2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Blue_1',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 40,
  },
];
List<Map<String,dynamic>> beltsPremium = [
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-1',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-3',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-4',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-5',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-6',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-7',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-8',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-8',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-9',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-10',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-11',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-12',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
  {
    'image': 'assets/images/belt.jpg',
    'title': 'Design-13',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 60,
  },
];
List<Map<String,dynamic>> tiesRegular = [
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Maroon_White',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Red_Black',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'White_Blue',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'White_LightBlue',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Blue_Redline-2',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Blue_Whiteline-2',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Brown_Whiteline-2',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
  {
'image': 'assets/images/tie.jpg',
'title': 'Green_Whiteline-2',
'rating': 5.0,
'days': 'Delivery in 7 days',
'rate': 30,
},
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Maroon_Whiteline-2',
    'rating': 5.0,
    'days': 'Delivery in 7 days',
    'rate': 30,
  },
];
List<Map<String,dynamic>> tiesPremium = [
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-1',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-2',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-3',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-4',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-5',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-6',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-7',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-8',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
  {
    'image': 'assets/images/tie.jpg',
    'title': 'Design-9',
    'rating': 5.0,
    'days': 'Delivery in 14 days',
    'rate': 50,
  },
];